import JSZip from "jszip";

interface ScsGeneratorOptions {
    engineCode: string;
    filename: string; // e.g. "c15_600.sii"
    truckInternalName: string; // e.g. "peterbilt.389"
    modName: string;
    author: string;
}

export const generateScsBlob = async ({
    engineCode,
    filename,
    truckInternalName,
    modName,
    author
}: ScsGeneratorOptions): Promise<Blob> => {
    const zip = new JSZip();

    // 1. Def Structure
    // Path: def/vehicle/truck/<truck>/engine/<filename>
    const safeTruckName = truckInternalName.trim() || "peterbilt.389"; // Default fallback
    const enginePath = `def/vehicle/truck/${safeTruckName}/engine/${filename}`;

    zip.file(enginePath, engineCode);

    // 2. Manifest
    const manifestContent = `SiiNunit
{
mod_package : .package_name
{
    package_version: "1.0"
    display_name: "${modName}"
    author: "${author}"
    category[]: "tuning_parts"
    icon: "mod_icon.jpg"
    description_file: "mod_description.txt"
}
}`;
    zip.file("manifest.sii", manifestContent);

    // 3. Description
    const descContent = `Engine Mod: ${modName}\nGenerated by Torque Architect\n\nTruck: ${safeTruckName}\nFile: ${filename}`;
    zip.file("mod_description.txt", descContent);

    // 4. (Optional) Icon - We could add a generate placeholder image if needed, but skipping for now to keep size low.
    // zip.file("mod_icon.jpg", blobData);

    // Generate Blob
    return await zip.generateAsync({ type: "blob" });
};
