import JSZip from "jszip";

export type ModFileType = 'engine' | 'transmission';

interface ScsGeneratorOptions {
    code: string;
    filename: string; // e.g. "c15_600.sii" or "eaton_18.sii"
    type: ModFileType;
    truckInternalName: string; // e.g. "peterbilt.389"
    modName: string;
    author: string;
}

export const generateScsBlob = async ({
    code,
    filename,
    type,
    truckInternalName,
    modName,
    author
}: ScsGeneratorOptions): Promise<Blob> => {
    const zip = new JSZip();

    // 1. Def Structure
    const safeTruckName = truckInternalName.trim() || "peterbilt.389";
    const subFolder = type === 'engine' ? 'engine' : 'transmission';
    const filePath = `def/vehicle/truck/${safeTruckName}/${subFolder}/${filename}`;

    zip.file(filePath, code);

    // 2. Manifest
    const manifestContent = `SiiNunit
{
mod_package : .package_name
{
    package_version: "1.0"
    display_name: "${modName}"
    author: "${author}"
    category[]: "tuning_parts"
    icon: "mod_icon.jpg"
    description_file: "mod_description.txt"
}
}`;
    zip.file("manifest.sii", manifestContent);

    // 3. Description
    const descContent = `${type === 'engine' ? 'Engine' : 'Transmission'} Mod: ${modName}\nGenerated by Powertrain Architect\n\nTruck: ${safeTruckName}\nFile: ${filename}`;
    zip.file("mod_description.txt", descContent);

    // Generate Blob
    return await zip.generateAsync({ type: "blob" });
};
