"use client";

import { Scale, FileText, Shield, Copyright } from "lucide-react";

export default function LegalPage() {
    return (
        <div className="max-w-4xl mx-auto space-y-12 pb-20">
            <header className="mb-8 border-b border-border pb-6">
                <h1 className="text-4xl font-bold tracking-tight text-foreground mb-4">Legal Information</h1>
                <p className="text-muted-foreground text-lg">
                    Terms regarding the use of Powertrain Architect.
                </p>
            </header>

            {/* Terms of Use */}
            <section className="space-y-4">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-accent/10 rounded-lg text-accent">
                        <FileText className="w-6 h-6" />
                    </div>
                    <h2 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-zinc-900 to-zinc-600 dark:from-white dark:to-zinc-400">
                        Terms of Use
                    </h2>
                </div>
                <div className="prose dark:prose-invert max-w-none bg-card p-6 rounded-xl border border-border">
                    <p><strong>Effective Date:</strong> December 16, 2025</p>
                    <p>
                        By using the <strong>Powertrain Architect</strong> software ("the Software"), you agree to the following terms:
                    </p>
                    <ol className="list-decimal pl-5 space-y-2 mt-4">
                        <li>
                            <strong>License</strong>: You are granted a revocable, non-exclusive, non-transferable, limited license to use the Software strictly in accordance with the terms of this Agreement.
                        </li>
                        <li>
                            <strong>Purpose</strong>: This Software is a third-party modification tool designed to assist in creating configuration files for <em>American Truck Simulator</em> and <em>Euro Truck Simulator 2</em>. It is not a game, and it is not intended to bypass any DRM or copyright protections of the base games.
                        </li>
                        <li>
                            <strong>User Responsibility</strong>: You acknowledge that any files generated by this Software are your sole responsibility. The creators of Powertrain Architect are not liable for any game instability, crashes, or data loss resulting from the use of generated files.
                        </li>
                    </ol>
                </div>
            </section>

            {/* Disclaimer */}
            <section className="space-y-4">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-red-500/10 rounded-lg text-red-500">
                        <Shield className="w-6 h-6" />
                    </div>
                    <h2 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-zinc-900 to-zinc-600 dark:from-white dark:to-zinc-400">
                        Disclaimer & Attribution
                    </h2>
                </div>
                <div className="prose dark:prose-invert max-w-none bg-card p-6 rounded-xl border border-border">
                    <p>
                        <strong>Not Affiliated with SCS Software:</strong>
                    </p>
                    <p>
                        "Powertrain Architect" is an unofficial fan project. <em>American Truck Simulator</em>, <em>Euro Truck Simulator 2</em>, and the specific truck designs depicted or referenced are the intellectual property of <strong>SCS Software</strong> and their respective license holders.
                    </p>
                    <p className="mt-4">
                        THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
                    </p>
                </div>
            </section>

            {/* Copyright */}
            <section className="space-y-4">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-emerald-500/10 rounded-lg text-emerald-500">
                        <Copyright className="w-6 h-6" />
                    </div>
                    <h2 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-zinc-900 to-zinc-600 dark:from-white dark:to-zinc-400">
                        Copyright
                    </h2>
                </div>
                <div className="prose dark:prose-invert max-w-none bg-card p-6 rounded-xl border border-border">
                    <p>
                        © 2025 Powertrain Architect Team. All Rights Reserved.
                    </p>
                    <p className="mt-2 text-sm text-muted-foreground">
                        Source code structure, custom algorithms for torque recommendation, and UI design are proprietary to the Powertrain Architect Team.
                    </p>
                </div>
            </section>
        </div>
    );
}
